version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r ci_requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=namedzip
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7